### ISSUE TITLE
咚漫

### ISSUE THREAD

**Issue by lovexme** [freedy82/Comic-Toolbox#1]
www.dongmanmanhua.cn
大佬能添加简体咚漫（webtoon）吗

**Comment by freedy82** [comment]
我最近不在家，可能要1-2個月之後才可以更新😂

**Comment by lovexme** [comment]
竟然回复了，谢谢



---原始邮件---
发件人: "Freedy ***@***.***&gt;
发送时间: 2022年5月31日(周二) 上午6:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [freedy82/Comic-Toolbox] 咚漫 (Issue #1)




 
我最近不在家，可能要1-2個月之後才可以更新😂

**Comment by freedy82** [comment]
昨天剛回家😂, 已在新版本加了
